[[tool]]
  repo = "BurntSushi/ripgrep"
  pattern = "ripgrep-*-{{triple}}.tar.gz"
  bin = ["rg"]
  man = ["doc/rg.1"]
  completions = ["complete/_rg", "complete/rg.bash"]
  [tool.patterns]
    linux_amd64 = "ripgrep-*-x86_64-unknown-linux-musl.tar.gz"

[[tool]]
  repo = "casey/just"
  pattern = "just-*-{{triple}}.tar.gz"
  bin = ["just"]
  man = ["just.1"]
  completions = ["completions/just.zsh", "completions/just.bash"]
  [tool.patterns]
    linux_amd64 = "just-*-x86_64-unknown-linux-musl.tar.gz"

[[tool]]
  repo = "ClementTsang/bottom"
  pattern = "bottom_{{triple}}.tar.gz"
  bin = ["btm"]
  completions = ["completion/_btm", "completion/btm.bash"]

[[tool]]
  repo = "lusingander/serie"
  pattern = "serie-*-{{triple}}.tar.gz"
  bin = ["serie"]

[[tool]]
  repo = "sharkdp/fd"
  pattern = "fd-*-{{triple}}.tar.gz"
  bin = ["fd"]
  man = ["fd.1"]
  completions = ["autocomplete/_fd", "autocomplete/fd.bash"]

[[tool]]
  repo = "spinel-coop/rv"
  pattern = "rv-{{triple}}.tar.xz"
  bin = ["rv", "rvx"]

[[tool]]
  repo = "astral-sh/uv"
  pattern = "uv-{{triple}}.tar.gz"
  bin = ["uv", "uvx"]

[[tool]]
  repo = "direnv/direnv"
  pattern = "direnv.{{os}}-{{arch}}"
  bin = ["direnv.{{os}}-{{arch}}:direnv"]

[[tool]]
  repo = "junegunn/fzf"
  pattern = "fzf-*-{{os}}_{{arch}}.tar.gz"
  bin = ["fzf"]

[[tool]]
  repo = "mikefarah/yq"
  pattern = "yq_{{os}}_{{arch}}.tar.gz"
  bin = ["yq_{{os}}_{{arch}}:yq"]
  man = ["yq.1"]

[[tool]]
  repo = "jqlang/jq"
  pattern = "jq-{{platform}}-{{arch}}"
  bin = ["jq-{{platform}}-{{arch}}:jq"]

[[tool]]
  repo = "koalaman/shellcheck"
  pattern = "shellcheck-*.{{os}}.{{gnuarch}}.tar.gz"
  bin = ["shellcheck"]

[[tool]]
  repo = "Schniz/fnm"
  pattern = "fnm-{{platform}}.zip"
  bin = ["fnm"]

[[tool]]
  repo = "neovim/neovim"
  pattern = "nvim-{{platform}}-{{arch}}.tar.gz"
  bin = ["nvim"]
  man = ["share/man/man1/nvim.1"]
  [tool.patterns]
    darwin_amd64 = "nvim-macos-x86_64.tar.gz"
    linux_amd64 = "nvim-linux-x86_64.tar.gz"

[[tool]]
  repo = "tree-sitter/tree-sitter"
  pattern = "tree-sitter-cli-{{platform}}-{{arch}}.zip"
  bin = ["tree-sitter"]
  [tool.patterns]
    darwin_amd64 = "tree-sitter-cli-macos-x64.zip"
    linux_amd64 = "tree-sitter-cli-linux-x64.zip"

[[tool]]
  repo = "denoland/deno"
  pattern = "deno-{{triple}}.zip"
  bin = ["deno"]
