[[tool]]
  repo = "BurntSushi/ripgrep"
  bin = ["rg"]
  man = ["doc/rg.1"]
  completions = ["complete/_rg", "complete/_rg.ps1", "complete/rg.bash", "complete/rg.fish"]
  [tool.patterns]
    darwin_amd64 = "ripgrep-{{tag}}-x86_64-apple-darwin.tar.gz"
    darwin_arm64 = "ripgrep-{{tag}}-aarch64-apple-darwin.tar.gz"
    linux_amd64 = "ripgrep-{{tag}}-x86_64-unknown-linux-musl.tar.gz"
    linux_arm64 = "ripgrep-{{tag}}-aarch64-unknown-linux-gnu.tar.gz"

[[tool]]
  repo = "casey/just"
  pattern = "just-{{tag}}-{{musltriple}}.tar.gz"
  bin = ["just"]
  man = ["just.1"]
  completions = ["completions/just.bash", "completions/just.fish", "completions/just.zsh"]

[[tool]]
  repo = "ClementTsang/bottom"
  pattern = "bottom_{{musltriple}}.tar.gz"
  bin = ["btm"]
  completions = ["completion/_btm", "completion/_btm.ps1", "completion/btm.bash", "completion/btm.fish"]

[[tool]]
  repo = "lusingander/serie"
  pattern = "serie-*-{{musltriple}}.tar.gz"
  bin = ["serie"]

[[tool]]
  repo = "sharkdp/fd"
  pattern = "fd-{{tag}}-{{musltriple}}.tar.gz"
  bin = ["fd"]
  man = ["fd.1"]
  completions = ["autocomplete/_fd", "autocomplete/_fd.ps1", "autocomplete/fd.bash", "autocomplete/fd.fish"]

[[tool]]
  repo = "spinel-coop/rv"
  pattern = "rv-{{musltriple}}.tar.xz"
  bin = ["rv", "rvx"]

[[tool]]
  repo = "astral-sh/uv"
  pattern = "uv-{{musltriple}}.tar.gz"
  bin = ["uv", "uvx"]

[[tool]]
  repo = "direnv/direnv"
  pattern = "direnv.{{os}}-{{arch}}"
  bin = ["direnv.{{os}}-{{arch}}:direnv"]

[[tool]]
  repo = "junegunn/fzf"
  pattern = "fzf-*-{{os}}_{{arch}}.tar.gz"
  bin = ["fzf"]

[[tool]]
  repo = "mikefarah/yq"
  pattern = "yq_{{os}}_{{arch}}.tar.gz"
  bin = ["yq_{{os}}_{{arch}}:yq"]
  man = ["yq.1"]

[[tool]]
  repo = "jqlang/jq"
  pattern = "jq-{{platform}}-{{arch}}"
  bin = ["jq-{{platform}}-{{arch}}:jq"]

[[tool]]
  repo = "koalaman/shellcheck"
  pattern = "shellcheck-{{tag}}.{{os}}.{{gnuarch}}.tar.gz"
  bin = ["shellcheck"]

[[tool]]
  repo = "Schniz/fnm"
  bin = ["fnm"]
  [tool.patterns]
    darwin_amd64 = "fnm-macos.zip"
    darwin_arm64 = "fnm-macos.zip"
    linux_amd64 = "fnm-linux.zip"
    linux_arm64 = "fnm-arm64.zip"

[[tool]]
  repo = "neovim/neovim"
  bin = ["nvim"]
  man = ["share/man/man1/nvim.1"]
  [tool.patterns]
    darwin_amd64 = "nvim-macos-x86_64.tar.gz"
    darwin_arm64 = "nvim-macos-arm64.tar.gz"
    linux_amd64 = "nvim-linux-x86_64.tar.gz"
    linux_arm64 = "nvim-linux-arm64.tar.gz"

[[tool]]
  repo = "tree-sitter/tree-sitter"
  bin = ["tree-sitter"]
  [tool.patterns]
    darwin_amd64 = "tree-sitter-cli-macos-x64.zip"
    darwin_arm64 = "tree-sitter-cli-macos-arm64.zip"
    linux_amd64 = "tree-sitter-cli-linux-x64.zip"
    linux_arm64 = "tree-sitter-cli-linux-arm64.zip"

[[tool]]
  repo = "denoland/deno"
  pattern = "deno-{{triple}}.zip"
  bin = ["deno", "deno:dx"]
