[settings]
idiomatic_version_file_enable_tools = ["rust"]
python.uv_venv_auto = "source"

[dotfiles]
"~/.config" = { source = "src/config", mode = "symlink-each" }

[dotfiles."~/.zshenv/xdg"]
comment = "#"
block = '''
export XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export MISE_CONFIG_DIR="${MISE_CONFIG_DIR:-$XDG_CONFIG_HOME/mise}"
export ZDOTDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}"

typeset -U path PATH
path=("$XDG_BIN_HOME" $path)
'''

[bootstrap.mise_shell_activate]
bash = true
zsh = true

[bootstrap.user]
login_shell = "/bin/zsh"

[tasks."bootstrap:git"]
usage = '''
arg "[name]" help="Git user.name"
arg "[email]" help="Git user.email"
'''
env = { GITCONFIG_FILE = "${GITCONFIG_FILE:-$HOME/.gitconfig}" }
description = "Configure Git settings and GitHub authentication"
interactive = true
run = [
  'gh auth status --active || gh auth login --web --clipboard --git-protocol=https',
  'git config set --file ${GITCONFIG_FILE} user.name "${usage_name:-$(gh api user --jq .name)}"',
  'git config set --file ${GITCONFIG_FILE} user.email "${usage_email:-$(gh api user --jq .login)@users.noreply.github.com}"',
  'gh auth setup-git --hostname github.com',
]

[tasks."bootstrap:git-lfs"]
description = "Configure Git LFS"
run = 'git lfs install --skip-repo'

[tasks."bootstrap:gcm"]
description = "Configure Git Credential Manager for Azure DevOps"
depends = ["bootstrap:git"]
run = 'git-credential-manager configure'
