[settings]
dotfiles.root = "~/Developer/dotfiles"
dotfiles.default_mode = "symlink-each"

[bootstrap.repos]
"~/Developer/dotfiles" = { url = "https://github.com/ascarter/dotfiles.git", ref = "main" }

[dotfiles]
"~/.config" = "config"

[dotfiles."~/.zshenv/xdg"]
comment = "#"
block = '''
export XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export ZDOTDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}"
export DOTFILES_HOME="${DOTFILES_HOME:-${HOME}/Developer/dotfiles}"

typeset -U path PATH
path=("$XDG_BIN_HOME" $path)
'''

[bootstrap.user]
login_shell = "/bin/zsh"

[bootstrap.mise_shell_activate]
zsh = true

[tasks.bootstrap]
description = "Reconcile the user environment"
depends_post = ["bootstrap:git", "bootstrap:git-lfs"]

[tasks."bootstrap:git"]
description = "Configure Git settings"
usage = '''
arg "[name]" help="Git user.name"
arg "[email]" help="Git user.email"
'''
env.GITCONFIG_FILE = "${HOME}/.gitconfig"
run = [
  'gh auth status --active || gh auth login --git-protocol=https --web --clipboard',
  'git config unset --file ${GITCONFIG_FILE} user.name || true',
  'git config unset --file ${GITCONFIG_FILE} user.email || true',
  'git config set --file ${GITCONFIG_FILE} user.name "${usage_name:-$(gh api user --jq .name)}"',
  'git config set --file ${GITCONFIG_FILE} user.email "${usage_email:-$(gh api user --jq .login)@users.noreply.github.com}"',
  'gh auth setup-git --hostname github.com'
]
quiet = true

[tasks."bootstrap:git-lfs"]
description = "Configure Git LFS"
run = 'git lfs install --skip-repo'
depends = ["bootstrap:git"]
quiet = true

[tasks."bootstrap:gcm"]
description = "Configure Git Credential Manager for Azure DevOps"
run = 'git-credential-manager configure'
depends = ["bootstrap:git"]
quiet = true
