[tools]
"aqua:spinel-coop/rv" = "latest"
bottom = "latest"
coreutils = "latest"
delta = "latest"
fastfetch = "latest"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
herdr = "latest"
neovim = "latest"
ripgrep = "latest"
rust = "latest"
tree-sitter = "latest"
usage = "latest"
