# Tools
brew "age"
brew "age-plugin-yubikey"
brew "btop"
brew "cmark-gfm"
brew "eza"
brew "htop"
brew "nvtop"
brew "shellcheck"
brew "shfmt"
brew "sqlite"
brew "uutils-coreutils"
brew "uutils-diffutils"
brew "uutils-findutils"

# Editors
brew "neovim"

if OS.mac?
  brew "gnupg"
  brew "pinentry"
  brew "pinentry-mac"
  brew "ykman"
  brew "yubico-piv-tool"

  cask_args adopt: true
  cask "bbedit"
  cask "chatgpt"
  cask "claude"
  cask "codex-app"
  cask "discord"
  cask "github"
  cask "ghostty"
  cask "hhkb"
  cask "logi-options+"
  cask "netnewswire"
  cask "obs"
  cask "obsidian"
  cask "proton-drive"
  cask "proton-mail"
  cask "proton-mail-bridge"
  cask "proton-pass"
  cask "protonvpn"
  cask "signal"
  cask "tailscale-app"
  cask "vivaldi"
  cask "visual-studio-code"
  cask "xquartz"
  cask "xscope"
  cask "yubico-authenticator"

  # My extras
  # tap "ascarter/extras"
  # brew "ascarter/extras/sk-libfido2"

  # 3rd party utilities
  tap "teamookla/speedtest"
  brew "teamookla/speedtest/speedtest"
end
