[shell_alias]
dotfiles-cd = 'cd "${DOTFILES_HOME}"'
dotfiles-update = 'git -C "${DOTFILES_HOME}" pull && mise -C "${DOTFILES_HOME}" bootstrap --update'
dotfiles-edit = '$EDITOR "${DOTFILES_HOME}"'
mdf = 'mise -C "${DOTFILES_HOME}"'
mr = 'mise run'
dircolors = 'coreutils dircolors'
ls = 'coreutils ls --group-directories-first --color=auto --human-readable'
la = 'ls -a -l'
ll = 'ls -l'
'l.' = 'ls -d .*'
htop = 'btm --basic'
sshpw = 'ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no'
dev = 'cd ${HOME}/Developer'
nvcurl = 'edcurl -e nvim'
zcurl = 'edcurl -e zed'
