[bootstrap.packages]
"apt:build-essential" = "latest"
"dnf:clang" = "latest"
"dnf:make" = "latest"
"dnf:ncurses" = "latest"
"dnf:ncurses-term" = "latest"
"dnf:pkgconf-pkg-config" = "latest"
"dnf:zsh" = "latest"

[bootstrap.hooks.post-packages]
run = ["mise run bootstrap:terminfo:ghostty"]
