# theme = "ansi"
theme = "base16_transparent"

[editor]
cursorline = false
color-modes = true
bufferline = "multiple"
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = ["version-control", "spacer", "separator", "file-type"]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "total-line-numbers",
  "position-percentage",
  "selections",
  "register",
  "file-encoding",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
"C-space" = "completion"

[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]

[keys.normal.g]
q = ":reflow"

[keys.normal.space]
q = ":quit"
w = ":write"
