[bootstrap.mise_shell_activate]
bash = true
zsh = true

[bootstrap.user]
login_shell = "/bin/zsh"

[dotfiles."~/.miserc.toml/profile"]
comment = "#"
source = "templates/miserc-profile.toml.tera"
template = "tera"
