# Terminal Light
# Author: Andrew Carter <@ascarter>

# Variation of dynamic Terminal theme optimized for light only

inherits = "terminal"

"ui.cursorline.primary" = { bg = "light-blue" }
"ui.cursorcolumn.primary" = { bg = "light-blue" }

"ui.gutter" = { bg = "light-gray" }
"ui.gutter.selected" = { bg = "light-gray", modifiers = ["bold"] }
"ui.statusline" = { bg = "light-gray", modifiers = ["bold"] }
"ui.statusline.inactive" = { bg = "light-gray", modifiers = ["dim"] }

"ui.menu" = { bg = "light-gray" }
"ui.popup" = { bg = "light-gray" }
"ui.window" = { fg = "light-gray", bg = "default" }

"ui.virtual" = { fg = "light-gray" }
"ui.virtual.ruler" = { bg = "light-gray" }
"ui.virtual.indent-guide" = { fg = "light-gray" }
"ui.virtual.inlay-hint" = { bg = "light-gray" }
