# Terminal Dark
# Author: Andrew Carter <@ascarter>

# Variation of dynamic Terminal theme optimized for dark only

inherits = "terminal"

"ui.cursorline.primary" = { bg = "black" }
"ui.cursorcolumn.primary" = { bg = "black" }

# "ui.gutter" = { bg = "black" }
# "ui.gutter.selected" = { bg = "black", modifiers = ["bold"] }
# "ui.statusline" = { bg = "black", modifiers = ["bold"] }
# "ui.statusline.inactive" = { bg = "black", modifiers = ["dim"] }

"ui.menu" = { bg = "black" }
"ui.popup" = { bg = "black" }

"ui.virtual.ruler" = { bg = "black" }
