[shell_alias]
dotfiles-cd = 'cd "${MISE_CONFIG_DIR}"'
dotfiles-update = 'mise bootstrap --from-git https://github.com/ascarter/dotfiles.git --update'
dotfiles-edit = '$EDITOR "${MISE_CONFIG_DIR}"'
mdf = 'mise -C "${MISE_CONFIG_DIR}"'
mr = 'mise run'
dircolors = 'coreutils dircolors'
ls = 'coreutils ls --group-directories-first --color=auto --human-readable'
la = 'ls -a -l'
ll = 'ls -l'
'l.' = 'ls -d .*'
htop = 'btm --basic'
sshpw = 'ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no'
dev = 'cd ${HOME}/Developer'
nvcurl = 'edcurl -e nvim'
zcurl = 'edcurl -e zed'
