[bootstrap.plugins]
rpm-ostree = "https://github.com/ascarter/mise-rpm-ostree"

[bootstrap.packages]
"rpm-ostree:bolt" = { version = "latest", os = "linux" }
"rpm-ostree:cosmic-monitor" = { version = "latest", os = "linux" }
"rpm-ostree:ghostty" = { version = "latest", os = "linux" }
#"rpm-ostree:proton-vpn-gnome-desktop" = "latest"
"rpm-ostree:solaar" = { version = "latest", os = "linux" }
"rpm-ostree:steam-devices" = { version = "latest", os = "linux" }
"rpm-ostree:zsh" = { version = "latest", os = "linux" }

[tasks."bootstrap:rpm:repos"]
description = "Configure Fedora package repositories"
hide = true
run = [
  { task = "bootstrap:rpm:copr", args = [
    "scottames/ghostty",
  ] },
  { task = "bootstrap:rpm:repo", args = [
    "https://pkgs.tailscale.com/stable/fedora/tailscale.repo",
  ] },
  { task = "bootstrap:rpm:repo", args = [
    "https://packages.microsoft.com/yumrepos/vscode/config.repo",
    "vscode.repo",
  ] },
]

[tasks."bootstrap:flatpak:repos"]
description = "Configure Flatpak repositories"
hide = true
run = [
  { task = "bootstrap:flatpak:remote", args = [
    "https://flathub.org/repo/flathub.flatpakrepo",
  ] },
  { task = "bootstrap:flatpak:remote", args = [
    "https://apt.pop-os.org/cosmic/cosmic.flatpakrepo",
  ] },
]

[bootstrap.hooks.pre-packages]
run = ["mise run bootstrap:rpm:repos", "mise run bootstrap:flatpak:repos"]

[tasks."bootstrap:apps:proton"]
description = "Install app RPM overlays"
run = [
  { task = "bootstrap:rpm:proton", args = [
    "proton-authenticator",
    "https://proton.me/download/authenticator/linux/version.json",
  ] },
  { task = "bootstrap:rpm:proton", args = [
    "proton-mail",
    "https://proton.me/download/mail/linux/version.json",
  ] },
  { task = "bootstrap:rpm:proton", args = [
    "proton-pass",
    "https://proton.me/download/PassDesktop/linux/x64/version.json",
  ] },
  { task = "bootstrap:rpm:proton", args = [
    "proton-meet",
    "https://proton.me/download/meet/linux/version.json",
  ] },
]
