# Set colorscheme
colorscheme default

# Disable terminal assistant graphic
set global ui_options terminal_assistant=none

# Display line numbers
add-highlighter global/ number-lines -hlcursor

# Highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# Always keep one line and three columns displayed around the cursor
set-option global scrolloff 1,3

# Softwrap long lines
# add-highlighter global/ wrap -word -indent

# Shortcut to quickly exit the editor
define-command -docstring "save and quit" x "write-all; quit"
