[tools]
"ubi:rails/rails-new" = "latest"
usage = "latest"
ruby = "latest"

[settings]
experimental = true

[settings.python]
uv_venv_auto = true

[env]
MISE_DEFAULT_CONFIG_FILENAME = ".mise/config.toml"
