# Coding in the Rain
# Light version
# Author: Andrew Carter <@ascarter>

# Minimal theme that reduces usage of color
# Uses only ANSI terminal 16 color values for portability
# Optimized for color sensitive users
# This modifies the default version to work with light backgrounds.

inherits = "coding_in_the_rain_dark"

# -------------------
# UI
# -------------------

"ui.cursorline.primary" = { fg = "white", bg = "light-gray" }
"ui.cursorcolumn.primary" = { fg = "white", bg = "light-gray" }
# "ui.cursor" = { fg = "white", bg = "black" }
# "ui.cursor" = { fg = "white", bg = "black" }
"ui.cursor.match" = { bg = "yellow", modifiers = ["bold"] }
# "ui.cursor.primary.insert" = { fg = "black", bg = "light-yellow", modifiers = ["bold"] }
# "ui.cursor.primary.select" = { fg = "default", bg = "blue", modifiers = ["bold"] }

"ui.selection" = { fg = "black", bg="light-gray" }
"ui.selection.primary" = { fg = "black", bg = "light-gray" }

# "ui.gutter.selected" = { bg = "light-gray", modifiers = ["bold"] }

# "ui.linenr" = { fg = "gray", modifiers = ["dim"] }
# "ui.linenr.selected" = { fg = "black", bg = "light-gray", modifiers = ["bold"] }

"ui.debug.active" = { fg = "blue", modifiers = ["bold"] }

# "ui.statusline" = { fg = "white", bg = "gray" }
"ui.statusline.inactive" = { fg = "default", bg = "light-gray", modifiers = ["dim"] }
"ui.statusline.normal" = { fg = "white", bg = "light-gray", modifiers = ["bold"] }
# "ui.statusline.insert" = { fg = "black", bg = "light-yellow", modifiers = ["bold"] }
# "ui.statusline.select" = { fg = "white", bg = "blue", modifiers = ["bold"] }

"ui.popup" = { bg = "light-gray" }
"ui.menu" = { fg= "black", bg = "light-gray" }
"ui.menu.scroll" = { fg = "gray", bg = "white" }
"ui.menu.selected" = { fg = "black", modifiers = ["bold"] }
"ui.window" = { fg = "light-gray", bg = "default" }

"ui.virtual" = { fg = "gray" }
"ui.virtual.ruler" = { bg = "gray" }
"ui.virtual.whitespace" = { fg = "light-gray", modifiers = ["dim"] }
"ui.virtual.indent-guide" = { fg = "gray", modifiers = ["dim"] }
"ui.virtual.inlay-hint" = { bg = "white" }

# -------------------
# Syntax Highlighting
# -------------------

# Match tree-sitter scopes
string = { fg = "gray",  modifiers = ["bold"] }
comment = { fg = "gray", modifiers = ["dim", "italic"] }
tag = "light-blue"
