# DuoTone
# Author: Andrew Carter <@ascarter>

# Port of DuoTone theme to Helix

# Full description:
# key = { fg = "#ffffff", bg = "#000000", underline = { color = "#ff0000", style = "curl"}, modifiers = ["bold", "italic"] }
#
# Foreground color only:
# key = "#ffffff"

# -------------------
# UI
# -------------------

"ui.text" = { fg="uno2" }
"ui.background" = { bg = "uno5" }
"ui.cursor" = { fg = "default", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "yellow", modifiers = ["bold"] }
"ui.cursor.primary.insert" = { fg = "black", bg = "light-yellow", modifiers = ["bold"] }
"ui.cursor.primary.select" = { fg = "default", bg = "blue", modifiers = ["bold"] }

"ui.cursorline.primary" = { bg = "black" }
"ui.cursorcolumn.primary" = { bg = "black" }

"ui.selection" = { fg = "light-gray", bg="gray" }
"ui.selection.primary" = { fg = "white", bg = "gray" }

"ui.gutter" = { bg = "default" }
"ui.gutter.selected" = { bg = "default", modifiers = ["bold"] }

"ui.linenr" = { modifiers = ["dim"] }
"ui.linenr.selected" = { modifiers = ["bold"] }

"ui.debug.breakpoint" = { fg = "red", modifiers = ["bold"] }
"ui.debug.active" = { fg = "yellow", modifiers = ["bold"] }

"ui.statusline" = { fg = "white", bg = "gray" }
"ui.statusline.separator" = { fg = "light-gray", modifiers = ["dim"] }
"ui.statusline.inactive" = { fg = "light-gray", modifiers = ["dim"] }
"ui.statusline.normal" = { fg = "white", bg = "gray", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "black", bg = "light-yellow", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "white", bg = "blue", modifiers = ["bold"] }

"ui.popup" = { bg = "gray" }
"ui.menu" = { bg = "gray" }
"ui.menu.scroll" = { fg = "blue", bg = "light-gray" }
"ui.menu.selected" = { fg = "white", modifiers = ["bold"] }
"ui.window" = { fg = "gray", bg = "default" }
"ui.help" = { fg = "default", bg = "default" }

"ui.virtual" = { fg = "gray" }
"ui.virtual.ruler" = { bg = "gray" }
"ui.virtual.whitespace" = { fg = "white" }
"ui.virtual.indent-guide" = { fg = "gray", modifiers = ["dim"] }
"ui.virtual.inlay-hint" = { bg = "black" }

warning = "yellow"
error = "red"
info = "light-gray"
hint = "cyan"

"diagnostic" = { underline = { color = "red", style = "curl" } }
"diagnostic.hint" = { underline = { color = "light-gray", style = "curl" } }
"diagnostic.info" = { underline = { color = "light-cyan", style = "curl" } }
"diagnostic.warning" = { underline = { color = "light-yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "light-red", style = "curl" } }

# -------------------
# Syntax Highlighting
# -------------------

# Match tree-sitter scopes
comment = { fg = "light-gray", modifiers = ["italic"] }
constant = { modifiers = ["bold"] }
string = { fg = "light-gray", modifiers = ["bold"] }
variable = { modifiers = ["bold", "italic"] }
function = { modifiers = ["bold"] }
tag = "light-blue"
namespace = { modifiers = ["bold"] }

# markup
"markup.heading" = { modifiers = ["bold"] }
"markup.list" = { modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["dim", "crossed_out"] }
"markup.link" = "light-blue"
"markup.quote" = { modifiers = ["dim", "italic"] }

# diff
"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "cyan"

[palette]
uno1 = "#ebebff"
uno2 = "#a8a8e6"
uno3 = "#9999cc"
uno4 = "#717184"
uno5 = "#51515c"
duo1 = "#71feb8"
duo2 = "#6cc699"
duo3 = "#70a48a"

