# Terminal
# Author: Andrew Carter <@ascarter>

# Terminal theme
# Uses only ANSI terminal 16 color values for portability
# Optimized for color sensitive users
# Adapts to dark or light terminal if terminal theme adapts
# Recommend using Apple terminal theme that uses dynamic colors
# for text, background and accents

# ANSI Color Names
#
# Idx  Name
# ---  -----------
#  -   default
#  0   black
#  1   red
#  2   green
#  3   yellow
#  4   blue
#  5   magenta
#  6   cyan
#  7   light-gray
#  8   gray
#  9   light-red
# 10   light-green
# 11   light-yellow
# 12   light-blue
# 13   light-magenta
# 14   light-cyan
# 15   white

# Full description:
# key = { fg = "#ffffff", bg = "#000000", underline = { color = "#ff0000", style = "curl"}, modifiers = ["bold", "italic"] }
#
# Foreground color only:
# key = "#ffffff"

# -------------------
# UI
# -------------------

"ui.text" = { fg="default" }
"ui.background" = { bg = "default" }
"ui.cursor" = { fg = "black", bg = "light-gray" }
"ui.cursor.match" = { fg = "black", bg = "yellow", modifiers = ["bold"] }

"ui.cursorline.primary" = { bg = "gray" }
"ui.cursorcolumn.primary" = { bg = "gray" }

"ui.selection" = { bg = "light-blue", modifiers = ["dim"] }
"ui.selection.primary" = { bg = "light-blue" }

"ui.gutter" = { bg = "gray" }
"ui.gutter.selected" = { bg = "gray", modifiers = ["bold"] }

"ui.linenr" = { modifiers = ["dim"] }
"ui.linenr.selected" = { modifiers = ["bold"] }

"ui.debug.breakpoint" = { fg = "red", modifiers = ["bold"] }
"ui.debug.active" = { fg = "yellow", modifiers = ["bold"] }

"ui.statusline" = { bg = "gray", modifiers = ["bold"] }
"ui.statusline.separator" = { modifiers = ["dim"] }
"ui.statusline.inactive" = { bg = "gray", modifiers = ["dim"] }
"ui.statusline.normal" = { modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "black", bg = "light-yellow", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "white", bg = "blue", modifiers = ["bold"] }

"ui.menu" = { bg = "gray" }
"ui.menu.selected" = { modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "blue", bg = "light-gray" }
"ui.popup" = { bg = "gray" }
"ui.help" = { fg = "default", bg = "default" }
"ui.window" = { fg = "gray", bg = "default" }

"ui.virtual" = { fg = "gray" }
"ui.virtual.ruler" = { bg = "gray" }
"ui.virtual.whitespace" = { modifiers = ["dim"] }
"ui.virtual.indent-guide" = { fg = "light-gray" }
"ui.virtual.inlay-hint" = { bg = "gray" }

warning = "yellow"
error = "red"
info = "default"
hint = "cyan"

"diagnostic" = { underline = { color = "red", style = "curl" } }
"diagnostic.hint" = { underline = { color = "white", style = "curl" } }
"diagnostic.info" = { underline = { color = "light-cyan", style = "curl" } }
"diagnostic.warning" = { underline = { color = "light-yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "light-red", style = "curl" } }

# -------------------
# Syntax Highlighting
# -------------------

# Match tree-sitter scopes
comment = { modifiers = ["italic"] }
constant = { modifiers = ["bold"] }
string = { modifiers = ["italic"] }
variable = { modifiers = ["italic"] }
function = { modifiers = ["bold"] }
tag = "blue"
namespace = { modifiers = ["bold"] }

# markup
"markup.heading" = { modifiers = ["bold"] }
"markup.list" = { modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["dim", "crossed_out"] }
"markup.link" = "blue"
"markup.quote" = { modifiers = ["italic"] }
"markup.raw.block" = { modifiers = ["italic"] }
"markup.raw.inline" = { modifiers = ["bold"] }

# diff
"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "cyan"

