# Terminal
# Author: Andrew Carter <@ascarter>

# Terminal theme
# Uses only ANSI terminal 16 color values for portability
# Optimized for color sensitive users
# Adapts to dark or light terminal if terminal theme adapts
# Recommend using Apple terminal theme that uses dynamic colors
# for text, background and accents
#
# This variant adjusts for strictly light mode palettes.
# Dynamic palette should not need to use this.

inherits = "terminal"

"ui.cursorline.primary" = { bg = "white" }
"ui.cursorcolumn.primary" = { bg = "white" }

"ui.selection" = { fg = "white", bg = "light-blue", modifiers = ["dim"] }
"ui.selection.primary" = { fg = "white", bg = "light-blue" }

"ui.gutter" = { bg = "white" }
"ui.gutter.selected" = { bg = "white", modifiers = ["bold"] }
"ui.statusline" = { bg = "white", modifiers = ["bold"] }
"ui.statusline.inactive" = { bg = "white", modifiers = ["dim"] }

"ui.menu" = { bg = "white" }
"ui.menu.scroll" = { fg = "blue", bg = "gray" }
"ui.popup" = { bg = "white" }
"ui.window" = { fg = "white", bg = "default" }

"ui.virtual" = { fg = "white" }
"ui.virtual.ruler" = { bg = "white" }
"ui.virtual.indent-guide" = { fg = "white" }
"ui.virtual.inlay-hint" = { bg = "white" }
