# Terminal
# Author: Andrew Carter <@ascarter>

# Terminal theme
# Uses only ANSI terminal 16 color values for portability
# Optimized for color sensitive users
# Adapts to dark or light terminal

# ANSI Color Names
# -----------
#   default
#   black
#   white
#   red
#   green
#   yellow
#   blue
#   magenta
#   cyan
#   gray
#   light-red
#   light-green
#   light-yellow
#   light-blue
#   light-magenta
#   light-cyan
#   light-gray

# Full description:
# key = { fg = "#ffffff", bg = "#000000", underline = { color = "#ff0000", style = "curl"}, modifiers = ["bold", "italic"] }
#
# Foreground color only:
# key = "#ffffff"

# -------------------
# UI
# -------------------

"ui.text" = { fg="default" }
"ui.background" = { bg = "default" }
"ui.cursor" = { fg = "default", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "yellow", modifiers = ["bold"] }
"ui.cursor.primary.insert" = { fg = "black", bg = "light-yellow", modifiers = ["bold"] }
"ui.cursor.primary.select" = { fg = "default", bg = "blue", modifiers = ["bold"] }

"ui.cursorline.primary" = { bg = "default", underline.style = "line" }

"ui.selection" = { fg = "white", bg = "blue" }
"ui.selection.primary" = { fg="white", bg = "blue", modifiers = ["bold"] }

"ui.gutter" = { bg = "default" }
"ui.gutter.selected" = { bg = "default", modifiers = ["bold"] }

"ui.linenr" = { modifiers = ["dim"] }
"ui.linenr.selected" = { modifiers = ["bold"] }

"ui.debug.breakpoint" = { fg = "red", modifiers = ["bold"] }
"ui.debug.active" = { fg = "yellow", modifiers = ["bold"] }

"ui.statusline" = { fg = "default", bg = "default" }
"ui.statusline.separator" = { fg = "default", modifiers = ["dim"] }
"ui.statusline.inactive" = { fg = "default", modifiers = ["dim"] }
"ui.statusline.normal" = { modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "black", bg = "light-yellow", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "white", bg = "blue", modifiers = ["bold"] }

"ui.popup" = { fg = "default", bg = "default", modifiers = ["reversed"] }
"ui.menu" = { fg = "default", bg = "default" }
"ui.menu.scroll" = { fg = "blue", bg = "gray" }
"ui.menu.selected" = { modifiers = ["bold"] }
"ui.window" = { fg = "gray", bg = "default" }
"ui.help" = { fg = "default", bg = "default", modifiers = ["reversed"] }

"ui.virtual" = { fg = "gray" }
"ui.virtual.ruler" = { bg = "gray" }
"ui.virtual.whitespace" = { fg = "white" }
"ui.virtual.indent-guide" = { fg = "gray", modifiers = ["dim"] }
"ui.virtual.inlay-hint" = { bg = "black" }

warning = "yellow"
error = "red"
info = "light-gray"
hint = "cyan"

"diagnostic" = { underline = { color = "red", style = "curl" } }
"diagnostic.hint" = { underline = { color = "light-gray", style = "curl" } }
"diagnostic.info" = { underline = { color = "light-cyan", style = "curl" } }
"diagnostic.warning" = { underline = { color = "light-yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "light-red", style = "curl" } }

# -------------------
# Syntax Highlighting
# -------------------

# Match tree-sitter scopes
comment = { fg = "light-gray", modifiers = ["italic"] }
constant = {fg = "white", modifiers = ["bold"] }
string = { fg = "light-gray", modifiers = ["bold"] }
variable = { modifiers = ["bold", "italic"] }
function = { modifiers = ["bold"] }
tag = "light-blue"
namespace = { modifiers = ["bold"] }

# markup
"markup.heading" = { modifiers = ["bold"] }
"markup.list" = { modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["dim", "crossed_out"] }
"markup.link" = "light-blue"
"markup.quote" = { modifiers = ["dim", "italic"] }

# diff
"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "cyan"

