theme = "coding_in_the_rain_dark"

[editor]
# true-color = true
cursorline = true
color-modes = true
auto-pairs = true
bufferline = "multiple"
# rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["version-control", "spacer", "separator", "file-type"]
right = ["diagnostics", "position", "total-line-numbers", "position-percentage", "selections", "register", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
"C-space" = "completion"
