# theme = "github_dark_colorblind"
theme = "developer"

[editor]
cursorline = true
true-color = true
color-modes = true
auto-pairs = true
bufferline = "multiple"
rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["version-control", "spacer", "separator", "file-type"]
right = ["diagnostics", "position", "total-line-numbers", "position-percentage", "selections", "register", "file-encoding"]

[editor.indent-guides]
render = true

[keys.insert]
"C-space" = "completion"
