" Set <space> as leader key
let mapleader = " "
let maplocalleader = " "

" Basic interface settings
set number
set relativenumber
set cursorline
set scrolloff=10
set mouse=a

" Use system clipboard
if has("nvim")
  " Neovim: schedule setting clipboard (to avoid timing issues)
  lua vim.schedule(function() vim.opt.clipboard = 'unnamedplus' end)
else
  " Vim: set clipboard if available
  if has("clipboard")
    set clipboard=unnamedplus
  endif
endif

" vim: ts=2 sts=2 sw=2 et
