# Linux platform configuration

[shell_alias]
about = 'fastfetch'
battery = 'upower --battery'
pbcopy = 'wl-copy'
pbpaste = 'wl-paste'

[bootstrap.packages]
"dnf:git" = "latest"
"dnf:zsh" = "latest"

[bootstrap.hooks.post-packages]
run = ["sudo dnf -y group remove 'libreoffice'"]
