# Workstation profile

[tasks.bootstrap]
description = "Bootstrap workstation environment"
depends_post = ["bootstrap:git", "bootstrap:git-lfs", "bootstrap:workstation"]

[tasks."bootstrap:workstation"]
description = "Bootstrap workstation applications"
depends = [
  "bootstrap:install:claude",
  "bootstrap:install:codex",
  "bootstrap:install:copilot",
  "bootstrap:install:zed",
]

[dotfiles."~/.miserc.toml/profile"]
comment = "#"
block = '''
env = ["workstation"]
'''

[bootstrap.brew]
adopt = true

[bootstrap.packages]
"brew-cask:bbedit" = "latest"
"brew-cask:chatgpt" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:github-copilot-app" = "latest"
"brew-cask:netnewswire" = "latest"
"brew-cask:obsidian" = "latest"
"brew-cask:proton-drive" = "latest"
"brew-cask:proton-mail" = "latest"
"brew-cask:proton-mail-bridge" = "latest"
"brew-cask:proton-meet" = "latest"
"brew-cask:proton-pass" = "latest"
"brew-cask:protonvpn" = "latest"
"brew-cask:signal" = "latest"
"brew-cask:spotify" = "latest"
"brew-cask:tailscale-app" = "latest"
"brew-cask:visual-studio-code" = "latest"
"brew-cask:vivaldi" = "latest"
"brew-cask:whatcable" = "latest"
"brew-cask:ascarter/extras/apple-container" = "latest"
"mas:6502835663" = "latest"                            # Proton Pass for Safari
"mas:497799835" = "latest"                             # Xcode

[tools]
