# macOS platform configuration

[shell_alias]
about='system_profiler SPHardwareDataType SPSoftwareDataType SPStorageDataType'
dequarantine='xattr -d com.apple.quarantine'
spotlight-rebuild='sudo mdutil -E /'
sysver='sw_vers'
protonmail-bridge='"/Applications/Proton Mail Bridge.app/Contents/MacOS/Proton Mail Bridge"'
tailscale='/Applications/Tailscale.app/Contents/MacOS/Tailscale'

[tools]
mas = "latest"

[bootstrap.macos.dock]
autohide = true
show_recents = true

[bootstrap.macos.finder]
show_all_files = true
show_pathbar = true
show_status_bar = true
preferred_view_style = "column"

[bootstrap.macos.keyboard]
press_and_hold = false

[bootstrap.macos.defaults]
"com.apple.finder" = { AppleShowAllFiles = true }
"com.apple.terminal" = { FocusFollowsMouse = true }
"NSGlobalDomain" = { "NSMenuEnableActionImages" = false }

[bootstrap.hooks.post-defaults]
run = [
  'killall Dock || true',
  'killall Finder || true'
]

[bootstrap.hooks.pre-packages]
run = 'xcode-select --install || true'

[bootstrap.packages]
"brew-cask:bbedit" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:netnewswire" = "latest"
"brew-cask:obsidian" = "latest"
"brew-cask:proton-mail" = "latest"
"brew-cask:proton-pass" = "latest"
"brew-cask:signal" = "latest"
"brew-cask:spotify" = "latest"
"brew-cask:tailscale-app" = "latest"
"brew-cask:visual-studio-code" = "latest"
"mas:6502835663" = "latest" # Proton Pass for Safari
"mas:497799835" = "latest" # Xcode
